version: '3.9'

services:
  web:
    image: devopsismail/flask-task-manager:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - flask_network
    restart: on-failure

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flask_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - flask_network

volumes:
  pgdata:


networks:
  flask_network:
    driver: bridge

